version: '3.3'

services: 
    db: 
        container_name: mySql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: pepito
            MYSQL_DATABASE: test_db 
            MYSQL_USER: pepito
            MYSQL_PASSWORD: pepito
        ports:
            - 6033:3306
        volumes: 
            - dbdata:/var/lib/mysql

        
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment: 
            - PMA_ARBITRARY=1
        restart: always
        ports: 
            - 8080:80

volumes: 
    dbdata: 

